name: Auto Assign PR Author

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Auto assign PR author
        uses: toshimaru/auto-author-assign@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
